server:
    port: 6667

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/readlater
        username: root
        password: 88888888
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
